/* Embeds the current bio-plane release into the wizard as a string, so the
 * wizard uploads exactly one module into the group's account and depends on
 * no repository, no CDN, and no second fetch at install time.
 *
 * Run from newgroup/: `npm run embed`. Expects the sibling ../bio-plane tree
 * with its devDependencies installed (esbuild does the bundling there).
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const plane = path.resolve(here, "../../bio-plane");
const out = path.resolve(here, "../src/release.mjs");

execSync("npm run build", { cwd: plane, stdio: "inherit" });
const src = readFileSync(path.join(plane, "dist/bio-plane.bundled.mjs"), "utf8");

/* The version the wizard installs and the version it verifies after an
   update are the same constant, read from the plane's wrangler config. */
const wcfg = readFileSync(path.join(plane, "wrangler.jsonc"), "utf8");
const version = /"VERSION":\s*"([^"]+)"/.exec(wcfg)?.[1];
if (!version) throw new Error("could not read VERSION from bio-plane/wrangler.jsonc");

/* Refuse to embed a release that still contains any published token value.
   The denylist protects the runtime; this protects the artifact. */
const secrets = readFileSync(path.join(plane, "dist/SECRETS.txt"), "utf8")
  .trim().split("\n").map((l) => l.split("=")[1]).filter(Boolean);
for (const s of secrets) {
  if (src.includes(s)) throw new Error("published token value found in the bundled release; refusing to embed");
}

mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(out,
  `/* GENERATED by scripts/embed-release.mjs. Do not edit. */\n`
  + `export const RELEASE_VERSION = ${JSON.stringify(version)};\n`
  + `export const RELEASE_SOURCE = ${JSON.stringify(src)};\n`);
console.log(`embedded bio-plane ${version}, ${src.length} chars, into src/release.mjs`);
