/* Embeds the current bio-plane release into the wizard as a string, so the
 * wizard uploads exactly one module into the group's account and depends on
 * no repository, no CDN, and no second fetch at install time.
 *
 * Run from newgroup/: `npm run embed`. Expects the sibling ../bio-plane tree
 * with its devDependencies installed (esbuild does the bundling there).
 *
 * WHY THIS REFUSES (D-106, 2026-07-31). The installer shipped 0.35.0 while the
 * plane ran 0.48.0, thirteen releases, and nobody noticed. The cause was not a
 * forgotten build step: this script read the embedded version out of
 * `bio-plane/wrangler.jsonc`, and NOTHING ELSE IN THE TREE READS THAT FIELD.
 * `scripts/deploy.mjs` binds VERSION from its command line, so every release
 * since 0.35.0 deployed correctly while the config literal sat untouched. A
 * field with exactly one reader, and that reader a build step whose output
 * nobody inspects, is a field that rots invisibly. Re-running the old script
 * today would still have embedded 0.35.0.
 *
 * So: `bio-plane/package.json` is the AUTHORITY, because that is the version a
 * release is cut from and the version RELEASE.json carries. Every other place
 * the version appears must agree with it or this refuses to build. The check is
 * equality, never a comparison: "newer" is not a defence, because a wrangler
 * config ahead of package.json is the same class of drift in the other
 * direction and equally worth stopping.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const SEMVER = /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;

/** Resolve the version to embed, or throw naming the disagreement.
 *
 *  Pure, taking the file CONTENTS rather than paths, so the refusal can be
 *  tested without a build and without a fixture tree on disk. Every throw says
 *  which file is authority and what to change, because the person who trips
 *  this is mid-release and should not have to read the script to act on it.
 */
export function resolveVersion({ packageJson, wranglerJsonc }) {
  let pkg;
  try { pkg = JSON.parse(packageJson); }
  catch (e) { throw new Error(`bio-plane/package.json does not parse: ${e.message}`); }

  const version = pkg && pkg.version;
  if (typeof version !== "string" || !SEMVER.test(version)) {
    throw new Error(
      `bio-plane/package.json has no usable "version" (got ${JSON.stringify(version)}). `
      + "It is the authority for what the installer embeds; nothing can be built without it.");
  }

  const m = /"VERSION":\s*"([^"]*)"/.exec(wranglerJsonc);
  if (!m) {
    throw new Error(
      "bio-plane/wrangler.jsonc declares no VERSION var. It is the version `wrangler dev` "
      + `binds locally, so it must agree with package.json (${version}) or local runs lie `
      + "about which plane they are.");
  }
  if (m[1] !== version) {
    throw new Error(
      "REFUSING TO EMBED: version sources disagree.\n"
      + `  bio-plane/package.json    ${version}   <- authority, cut releases from this\n`
      + `  bio-plane/wrangler.jsonc  ${m[1]}\n`
      + "This is D-106: wrangler.jsonc's VERSION has no other reader, so it drifts silently "
      + "and the installer ships whatever it last said. Set wrangler.jsonc to "
      + `"VERSION": "${version}" and build again.`);
  }
  return version;
}

/** Every published token value that must not survive into the artifact. */
export function publishedTokens(secretsTxt) {
  return secretsTxt.trim().split("\n").map((l) => l.split("=")[1]).filter(Boolean);
}

function main() {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const plane = path.resolve(here, "../../bio-plane");
  const out = path.resolve(here, "../src/release.mjs");

  /* Resolved BEFORE the build, so a disagreement costs a second rather than a
     full esbuild run, and so no stale artifact is left behind by a refusal. */
  const version = resolveVersion({
    packageJson: readFileSync(path.join(plane, "package.json"), "utf8"),
    wranglerJsonc: readFileSync(path.join(plane, "wrangler.jsonc"), "utf8"),
  });

  execSync("npm run build", { cwd: plane, stdio: "inherit" });
  const src = readFileSync(path.join(plane, "dist/bio-plane.bundled.mjs"), "utf8");

  /* Refuse to embed a release that still contains any published token value.
     The denylist protects the runtime; this protects the artifact. */
  for (const s of publishedTokens(readFileSync(path.join(plane, "dist/SECRETS.txt"), "utf8"))) {
    if (src.includes(s)) throw new Error("published token value found in the bundled release; refusing to embed");
  }

  mkdirSync(path.dirname(out), { recursive: true });
  writeFileSync(out,
    "/* GENERATED by scripts/embed-release.mjs. Do not edit. */\n"
    + `export const RELEASE_VERSION = ${JSON.stringify(version)};\n`
    + `export const RELEASE_SOURCE = ${JSON.stringify(src)};\n`);
  console.log(`embedded bio-plane ${version}, ${src.length} chars, into src/release.mjs`);
}

/* Importable for tests without running a build. */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
