#!/usr/bin/env node
/* Build the engine wasm and its glue, from `engine/` (IronCalc at the pinned commit, with its xlsx reader).
 *
 * The output is a GENERATED ARTIFACT this member owns and commits (PROCESS-MECHANICS §14): `assets/sheet-engine.wasm`,
 * `src/enginelib.mjs` and `src/enginelib-tz.mjs`. The fleet bundle's manifest pins the wasm's bytes (bundler R4), and
 * `src/contract.mjs` holds its length and SHA-256 as constants (R13), so a rebuild that changes a byte fails the
 * suite until those are updated on purpose.
 *
 * Run from sheet-worker/: `npm run build:engine` (needs rustup's `wasm32-unknown-unknown` target and
 * `wasm-bindgen-cli` at the version below: `cargo install wasm-bindgen-cli --version 0.2.126 --locked`). Then
 * `npm run build` for the bundle. Steps:
 *   1. refuses unless engine/Cargo.toml, engine/src/lib.rs and src/contract.mjs name the same IronCalc commit;
 *   2. `cargo build --release --locked --target wasm32-unknown-unknown`, with the build paths remapped so the bytes
 *      do not depend on where the checkout or the cargo home are;
 *   3. `wasm-bindgen --target web`;
 *   4. appends a custom section `bio-engine` naming the commit, the toolchain and the length and SHA-256 of the code
 *      before the section, which the member reads at run time (R13);
 *   5. renders the glue: its time-zone snippet becomes `enginelib-tz.mjs`, and `resetEngine()` is appended so the
 *      member can start each request on a fresh instance (R12);
 *   6. prints the wasm's length and SHA-256, and exits 1 when they are not `contract.mjs`'s constants.
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { ENGINE_VERSION, WASM_BYTES, WASM_SHA256, ENGINE_SECTION } from "../src/contract.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const ENGINE = join(ROOT, "engine");
export const WASM_BINDGEN_VERSION = "0.2.126";

const sha256 = (b) => createHash("sha256").update(b).digest("hex");
const run = (cmd, args, opts = {}) => execFileSync(cmd, args, { encoding: "utf8", ...opts });

/** The `bio-engine` custom section appended to `code`: id 0, size, name, JSON payload. */
export function withEngineSection(code, facts) {
  const leb = (n) => { const out = []; do { let b = n & 0x7f; n >>>= 7; if (n) b |= 0x80; out.push(b); } while (n); return out; };
  const name = Buffer.from(ENGINE_SECTION, "utf8");
  const payload = Buffer.from(JSON.stringify(facts), "utf8");
  const body = Buffer.concat([Buffer.from(leb(name.length)), name, payload]);
  return Buffer.concat([code, Buffer.from([0]), Buffer.from(leb(body.length)), body]);
}

/** The glue as committed: wasm-bindgen's output with the snippet import re-pointed and the reset appended. */
export function renderGlue(glue) {
  const SNIPPET = /^import \{ ic_tz_all, ic_tz_parts, ic_tz_validate \} from '\.\/snippets\/[^']+\/inline0\.js';$/m;
  if (!SNIPPET.test(glue)) throw new Error("wasm-bindgen's glue no longer imports the time-zone snippet as expected");
  if (!/^let wasmModule, wasmInstance, wasm;$/m.test(glue) || !/^let heap = new Array\(1024\)/m.test(glue))
    throw new Error("wasm-bindgen's glue no longer declares the state resetEngine() clears");
  return "/* GENERATED by scripts/build-engine.mjs from wasm-bindgen " + WASM_BINDGEN_VERSION + "'s glue for engine/ "
    + "(IronCalc " + ENGINE_VERSION + "). Do not edit; rebuild. */\n"
    + glue.replace(SNIPPET, "import { ic_tz_all, ic_tz_parts, ic_tz_validate } from './enginelib-tz.mjs';")
    + "\n/* Appended by the build: drop the instance and every cache tied to it, so the next initSync starts a fresh one. */\n"
    + "export function resetEngine() {\n"
    + "    wasm = undefined; wasmInstance = undefined; wasmModule = undefined;\n"
    + "    cachedDataViewMemory0 = null; cachedUint8ArrayMemory0 = null;\n"
    + "    heap = new Array(1024).fill(undefined); heap.push(undefined, null, true, false); heap_next = heap.length;\n"
    + "}\n";
}

function main() {
  const cargo = readFileSync(join(ENGINE, "Cargo.toml"), "utf8");
  const lib = readFileSync(join(ENGINE, "src/lib.rs"), "utf8");
  const revs = [...cargo.matchAll(/rev = "([0-9a-f]{40})"/g)].map((m) => m[1]);
  const libCommit = (lib.match(/pub const ENGINE_COMMIT: &str = "([0-9a-f]{40})";/) || [])[1];
  if (!revs.length || revs.some((r) => r !== ENGINE_VERSION) || libCommit !== ENGINE_VERSION) {
    console.error(`REFUSED [COMMIT_DISAGREES]: Cargo.toml ${JSON.stringify(revs)}, lib.rs ${libCommit}, `
      + `contract.mjs ${ENGINE_VERSION}`);
    process.exit(2);
  }
  const bindgen = run("wasm-bindgen", ["--version"]).trim();
  if (bindgen !== `wasm-bindgen ${WASM_BINDGEN_VERSION}`) {
    console.error(`REFUSED [WASM_BINDGEN_VERSION]: found "${bindgen}", need ${WASM_BINDGEN_VERSION}`);
    process.exit(2);
  }
  const rustc = run("rustc", ["--version"]).trim();
  const cargoHome = process.env.CARGO_HOME || join(homedir(), ".cargo");
  const target = process.env.CARGO_TARGET_DIR || join(ENGINE, "target");
  const RUSTFLAGS = [`--remap-path-prefix=${cargoHome}=/cargo`, `--remap-path-prefix=${ENGINE}=/engine`].join(" ");
  run("cargo", ["build", "--release", "--locked", "--target", "wasm32-unknown-unknown"],
    { cwd: ENGINE, stdio: "inherit", env: { ...process.env, CARGO_TARGET_DIR: target, RUSTFLAGS } });

  const out = mkdtempSync(join(tmpdir(), "sheet-engine-"));
  run("wasm-bindgen", ["--target", "web", "--out-dir", out, "--out-name", "sheet_engine",
    join(target, "wasm32-unknown-unknown/release/sheet_engine.wasm")]);
  const code = readFileSync(join(out, "sheet_engine_bg.wasm"));
  const wasm = withEngineSection(code, {
    engine: "ironcalc", commit: ENGINE_VERSION, features: ["xlsx"], rustc, wasm_bindgen: WASM_BINDGEN_VERSION,
    code_bytes: code.length, code_sha256: sha256(code),
  });
  writeFileSync(join(ROOT, "assets/sheet-engine.wasm"), wasm);
  const snippetDir = readdirSync(join(out, "snippets"))[0];
  writeFileSync(join(ROOT, "src/enginelib-tz.mjs"),
    "/* GENERATED by scripts/build-engine.mjs: IronCalc's time-zone helpers (its `browser_tz.rs` inline JS). */\n"
    + readFileSync(join(out, "snippets", snippetDir, "inline0.js"), "utf8").replace(/^\s+/gm, (s) => s.replace(/^ {8}/, "")));
  writeFileSync(join(ROOT, "src/enginelib.mjs"), renderGlue(readFileSync(join(out, "sheet_engine.js"), "utf8")));

  const facts = { bytes: wasm.length, sha256: sha256(wasm) };
  console.log(`sheet-worker: assets/sheet-engine.wasm ${facts.bytes} B, sha256 ${facts.sha256} (${rustc})`);
  if (facts.bytes !== WASM_BYTES || facts.sha256 !== WASM_SHA256) {
    console.error(`sheet-worker: contract.mjs pins ${WASM_BYTES} B / ${WASM_SHA256}; set WASM_BYTES and WASM_SHA256 `
      + `to the values above if this rebuild is intended.`);
    process.exit(1);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
