/* THE VENDOR GLUE, PATCHED DETERMINISTICALLY AND COMMITTED — the
 * `src/signpage.mjs` shape, one member over.
 *
 * ---- WHY THERE IS A PATCH AT ALL, AND IT IS MEASURED RATHER THAN PREFERRED --
 *
 * `tesseract-wasm`'s own `dist/lib.js` starts its engine by handing emscripten a
 * wasm BUFFER (`WebAssembly.instantiate(bytes)`). **Workers forbid runtime wasm
 * compilation**, so that path cannot run inside an isolate at all, and the only
 * entry point that can is emscripten's `instantiateWasm` hook — the one line that
 * does `new WebAssembly.Instance(module, imports)` over a module the PLATFORM
 * compiled at upload time. The vendor's `createOCREngine` does not accept that
 * hook, and it does not accept `locateFile` either; without the second,
 * emscripten evaluates `new URL("tesseract-core.wasm", import.meta.url)` and
 * workerd throws `TypeError: Invalid URL string.`
 *
 * Both facts were MEASURED by CPDF-15 (2026-09-10, `MEASUREMENTS.md`) on a
 * deployed scratch Worker, each by being refused. This file applies the same TWO
 * anchored substitutions that probe applied, and nothing else.
 *
 * ---- WHY THE OUTPUT IS COMMITTED RATHER THAN BUILT FROM node_modules --------
 *
 * Because a fleet member must be buildable and TESTABLE in a checkout with no
 * install of its own — `battery.mjs` skips a member whose suite cannot resolve
 * its imports, and "a guard that skips is not a guard" is FL-9's whole sentence.
 * So `tesseract-wasm` is a devDependency, the patched glue is a COMMITTED
 * first-party source hashed by the bundle manifest like any other, and the
 * member vendors NOTHING at runtime.
 *
 * That trade has a cost and the cost is the one `src/signpage.mjs` already pays:
 * a committed generated file can go stale against its generator. The closure is
 * the same too — `fleetbundles.test.mjs` re-renders THIS function in memory and
 * compares it against the committed module, so a changed vendor whose render was
 * never re-run FAILS at the gate instead of at the next build. The one honest
 * difference: that arm needs the vendor present, so on a checkout with no member
 * install it SKIPS BY NAME. The vendor digest below is what covers that case —
 * a vendor version this patch was never measured against refuses rather than
 * being patched on a hope.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** The vendor file this patch was measured against, BY DIGEST. Identical to
 *  CPDF-15's `PIN_LIB` — reproduced here from a fresh install rather than copied
 *  forward, and the two agreeing is a comparability fact worth having: this
 *  member runs the same glue the GO verdict was measured on. */
export const VENDOR_SHA256 = "ed6b39d775484081affa3d21bf491f705673c2a3fd616b2f7bce9020ed8eba13";
export const VENDOR_BYTES = 97684;

/** Where the vendor lives (present only where the devDependency is installed)
 *  and where the render is committed. */
export const TESSLIB_VENDOR = fileURLToPath(
  new URL("../node_modules/tesseract-wasm/dist/lib.js", import.meta.url));
export const TESSLIB_OUT = fileURLToPath(new URL("../src/tesslib.mjs", import.meta.url));

/** The two substitutions, and they are ANCHORED: each `from` is asserted present
 *  before either is applied, so a vendor whose shape moved stops this rather
 *  than silently shipping an engine that cannot start. Copied from CPDF-15's
 *  `LIB_PATCHES` because they are the same two edits, measured once. */
export const PATCHES = [
  ["async function createOCREngine({ wasmBinary, progressChannel, } = {}) {\n    if (!wasmBinary) {",
   "async function createOCREngine({ wasmBinary, progressChannel, instantiateWasm, locateFile, } = {}) {\n    if (!wasmBinary && !instantiateWasm) {"],
  ["const tessLib = await Module({ wasmBinary });",
   "const tessLib = await Module({ wasmBinary, instantiateWasm, locateFile });"],
];

const HEADER = `/* GENERATED by ocr-worker/scripts/embed-tesslib.mjs from
 * node_modules/tesseract-wasm/dist/lib.js (tesseract-wasm@0.11.0,
 * sha256 ${VENDOR_SHA256}, ${VENDOR_BYTES} B).
 * DO NOT EDIT. Two anchored substitutions are applied and no other line of the
 * vendor's code is touched; read the generator for why each one exists and
 * which measurement refused the alternative. The gate
 * bio-plane/test/fleetbundles.test.mjs re-renders this in memory and FAILS on a
 * stale render, wherever the vendor is installed. */
`;

export const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

/** Render the patched glue from the vendor's own source.
 *
 *  THROWS on a vendor digest this patch was not measured against, and THROWS on
 *  a missing anchor. Both are refusals rather than warnings: an unpatched or
 *  half-patched engine does not fail at build time, it fails at the first OCR
 *  call inside an isolate, which is the worst place to find out. */
export function renderTessLib(vendorSrc) {
  const got = sha256(Buffer.from(vendorSrc, "utf8"));
  if (got !== VENDOR_SHA256)
    throw new Error(`tesseract-wasm's dist/lib.js is sha256 ${got}, this patch was measured `
      + `against ${VENDOR_SHA256}. The two substitutions are anchored on that exact file; `
      + `re-measure the engine (CPDF-15's probe is the instrument) before moving this pin.`);
  let out = vendorSrc;
  for (const [from] of PATCHES)
    if (!out.includes(from))
      throw new Error(`ANCHOR MISSING in tesseract-wasm's dist/lib.js: ${JSON.stringify(from.slice(0, 60))}…`
        + ` — refusing to ship an engine that cannot start.`);
  for (const [from, to] of PATCHES) out = out.replace(from, to);
  return HEADER + out;
}

/** Read the vendor and render. Returns null where the vendor is not installed,
 *  which is the normal condition in a checkout that never ran `npm ci` here —
 *  NAMED by the caller, never treated as a pass. */
export function renderFromVendor() {
  let src;
  try { src = readFileSync(TESSLIB_VENDOR, "utf8"); } catch { return null; }
  return renderTessLib(src);
}
