/* NEGATIVE CONTROL: (run 2026-07-31) corrupt the SSHSIG signed-preimage magic in verifySshsig ("SSHSIG" -> "SSHXIG") so the preimage disagrees with what OpenSSH signs -> 2 assertions fail (fresh signature verifies; fresh signature bound to its bytes); restored, 18 pass. (With ssh-keygen absent the same 2 are the named skips, so the control targets exactly the fresh path.) */
/* SSHSIG conformance: this module must agree with stock OpenSSH.
 *
 * Negative-control detail: corrupt the SSHSIG signed-preimage magic in verifySshsig ("SSHSIG" -> "SSHXIG") so the preimage disagrees with what OpenSSH signs -> 2 assertions fail (fresh signature verifies; fresh signature bound to its bytes); restored, 18 pass. (With ssh-keygen absent the same 2 are the named skips, so the control targets exactly the fresh path.)
 *
 * Fixtures are generated fresh by ssh-keygen on every run when it is
 * available, so agreement is with the installed OpenSSH, not with a frozen
 * blob. When ssh-keygen is absent the suite falls back to pinned fixtures
 * generated by OpenSSH 9.6p1, so the suite still runs everywhere — but the two
 * fresh-signature cases genuinely cannot run, so the tail line NAMES them and
 * counts them as skipped rather than silently reporting 16 where a machine with
 * ssh-keygen reports 18 (the 16-vs-18 half of D-93).
 *
 * NEGATIVE CONTROL: drop the `skip` note from the tail line and hide ssh-keygen
 * from PATH -> the battery reads a bare `16 pass` with no hint that two cases
 * were skipped — the exact silent shortfall of D-93. With the note it reads
 * `16 pass, 0 fail, 2 skip (fresh signature verifies; fresh signature bound to
 * its bytes; ssh-keygen absent)`. (Run 2026-07-31, M0-4: with ssh-keygen hidden,
 * the note names both cases; with ssh-keygen present, 18 pass and no skip note.)
 */
import "./stdio.mjs";                 /* D-282: a suite's own exit must not discard the suite's own output */
import "./sandbox.mjs"; /* D-186: owns $TMPDIR for this process and removes it on exit */
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { verifySshsig, parseSshsig, parsePubkeyLine, normalizeKey,
         ratifyStatement, NS_RELEASE, NS_RATIFY } from "../src/sshsig.mjs";

let pass = 0, fail = 0;
const skipped = [];
const t = (label, got, want) => {
  const ok = JSON.stringify(got) === JSON.stringify(want);
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${label}${ok ? "" : `\n         want ${JSON.stringify(want)}\n         got  ${JSON.stringify(got)}`}`);
  ok ? pass++ : fail++;
};

/* Pinned fixtures (OpenSSH 9.6p1, key generated for this suite, no secret
   retained): message "hello bio release\n", namespace bio-release. */
const PINNED = {
  pub: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMAATz95Xd15iuuK5zLFjBydY8u2jG37egk1MvtDAph sparky-release",
  msg: "hello bio release\n",
  ns: "bio-release",
  sig: `-----BEGIN SSH SIGNATURE-----
U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAg4wABPP3ld3XmK64rnMsWMHJ1jy
7aMbft6CTUy+0MCmEAAAALYmlvLXJlbGVhc2UAAAAAAAAABnNoYTUxMgAAAFMAAAALc3No
LWVkMjU1MTkAAABAk3JISyJJOyePcA2Oge+Juv5QR/QDQxZHAsEdPXWR1aXgHZ+Mr4lkQL
2y4ylxfMGENlue22wQJPGLDCquud/hCQ==
-----END SSH SIGNATURE-----
`,
};

function freshFixture() {
  try {
    const dir = mkdtempSync(join(tmpdir(), "sshsig-"));
    execFileSync("ssh-keygen", ["-t", "ed25519", "-N", "", "-C", "fresh", "-f", join(dir, "k"), "-q"]);
    const msg = `fresh message ${Date.now()}\n`;
    writeFileSync(join(dir, "m"), msg);
    execFileSync("ssh-keygen", ["-Y", "sign", "-f", join(dir, "k"), "-n", NS_RATIFY, join(dir, "m")],
      { stdio: ["ignore", "ignore", "ignore"] });
    return { pub: readFileSync(join(dir, "k.pub"), "utf8").trim(),
             msg, ns: NS_RATIFY,
             sig: readFileSync(join(dir, "m.sig"), "utf8"), dir };
  } catch { return null; }
}

const enc = (s) => new TextEncoder().encode(s);

console.log("\n--- parsing ---");
const p = parseSshsig(PINNED.sig);
t("pinned sig parses to version 1", p.version, 1);
t("pinned sig namespace", p.namespace, "bio-release");
t("pinned sig hash", p.hashAlg, "sha512");
t("pinned key matches pubkey line", p.pubB64, parsePubkeyLine(PINNED.pub).b64);
t("normalizeKey on full line", normalizeKey(PINNED.pub), parsePubkeyLine(PINNED.pub).b64);
t("normalizeKey on allowed_signers line",
  normalizeKey("sparky " + PINNED.pub.split(" ").slice(0, 2).join(" ")), parsePubkeyLine(PINNED.pub).b64);
t("normalizeKey on bare b64", normalizeKey(PINNED.pub.split(" ")[1]), parsePubkeyLine(PINNED.pub).b64);
t("normalizeKey rejects rsa", normalizeKey("ssh-rsa AAAAB3Nza garbage"), null);

console.log("\n--- verification against pinned OpenSSH output ---");
const allowed = [PINNED.pub];
t("good signature verifies",
  (await verifySshsig(PINNED.sig, enc(PINNED.msg), PINNED.ns, allowed)).ok, true);
t("wrong namespace refused",
  (await verifySshsig(PINNED.sig, enc(PINNED.msg), "bio-ratify", allowed)).reason, "NAMESPACE");
t("unknown key refused",
  (await verifySshsig(PINNED.sig, enc(PINNED.msg), PINNED.ns, [])).reason, "UNKNOWN_KEY");
t("tampered message refused",
  (await verifySshsig(PINNED.sig, enc(PINNED.msg + "x"), PINNED.ns, allowed)).reason, "BAD_SIGNATURE");
const flipped = PINNED.sig.replace("hCQ==", "hCq==");
t("tampered signature refused or malformed",
  ["BAD_SIGNATURE", "MALFORMED"].includes((await verifySshsig(flipped, enc(PINNED.msg), PINNED.ns, allowed)).reason ?? "ok"), true);
t("garbage armor is MALFORMED, not a throw",
  (await verifySshsig("not a signature", enc("x"), PINNED.ns, allowed)).reason, "MALFORMED");

console.log("\n--- verification against fresh ssh-keygen output ---");
const f = freshFixture();
if (f) {
  t("fresh signature verifies", (await verifySshsig(f.sig, enc(f.msg), f.ns, [f.pub])).ok, true);
  t("fresh signature bound to its bytes",
    (await verifySshsig(f.sig, enc(f.msg.toUpperCase()), f.ns, [f.pub])).reason, "BAD_SIGNATURE");
} else {
  skipped.push("fresh signature verifies", "fresh signature bound to its bytes");
  console.log("  SKIP  fresh signature verifies — ssh-keygen not on PATH");
  console.log("  SKIP  fresh signature bound to its bytes — ssh-keygen not on PATH");
  console.log("        (pinned OpenSSH 9.6p1 fixtures above already cover parse + verify)");
}

console.log("\n--- canonical statements ---");
t("ratify statement is stable bytes",
  new TextDecoder().decode(ratifyStatement("INFO-2026-0001-x", "ab".repeat(32))),
  `bio-ratify INFO-2026-0001-x ${"ab".repeat(32)}\n`);
t("namespaces are distinct", NS_RELEASE === NS_RATIFY, false);

const skipNote = skipped.length
  ? `, ${skipped.length} skip (${skipped.join("; ")}; ssh-keygen absent)` : "";
console.log(`\nsshsig: ${pass} pass, ${fail} fail${skipNote}`);
process.exit(fail ? 1 : 0);
