#!/usr/bin/env python3
"""Each unit's state, read from its output file alone; writes STATE.md. Run from anywhere."""
import os, re, glob
S = os.path.dirname(os.path.abspath(__file__))
def out_path(uid):
    if uid.startswith("A-"): return f"studies/{uid[2:]}.md"
    if uid.startswith("R-"): return f"reviews/{uid}.md"
    return f"notes/{uid}.md"
def state(uid):
    p = f"{S}/{out_path(uid)}"
    if not os.path.exists(p): return "missing", ""
    t = open(p, encoding="utf-8").read()
    if uid.startswith("A-"):
        return ("done", "") if re.search(r"^##\s*9\.?\s|Sources opened", t, re.M) else ("partial", "sections 1-9 not all written")
    if uid.startswith("R-"):
        return ("done", "") if "## Verdict" in t else ("partial", "no verdict yet")
    cert = re.search(r"^## Reading certificate\n(.*?)(?=^## )", t, re.S | re.M)
    finished = "## Cross-construct observations" in t
    lines = [l for l in (cert.group(1).splitlines() if cert else []) if l.strip().startswith("-")]
    incomplete = [l.strip() for l in lines if "complete" not in l.lower() or re.search(r"stopped|partial|incomplete", l, re.I)]
    if finished and lines and not incomplete: return "done", ""
    return "partial", ("; ".join(incomplete) or "note unfinished")[:300]
units = sorted(os.path.basename(p)[:-4] for p in glob.glob(f"{S}/prompts/*.txt"))
order = lambda u: (u.startswith("A-"), u.startswith("R-"), u[0], int(re.sub(r"\D", "", u) or 0), u)
rows = [(u, *state(u)) for u in sorted(units, key=order)]
digests = sorted(os.path.basename(p) for p in glob.glob(f"{S}/digest/*.md"))
with open(f"{S}/STATE.md", "w", encoding="utf-8") as f:
    f.write("# Study state (generated by status.py; do not edit by hand)\n\n")
    f.write("| unit | prompt | output | state | note |\n|---|---|---|---|---|\n")
    for u, st, note in rows: f.write(f"| {u} | prompts/{u}.txt | {out_path(u)} | {st} | {note} |\n")
    f.write(f"\nDigests built: {', '.join(digests) or 'none'}\n")
for u, st, note in rows: print(f"{u:16} {st:8} {note}")
print("digests:", digests or "none")
