/* case-checker — the build of the standalone program (requirements: `build/requirements/case-checker.md` R13; DEC-112
 * (3): "a standalone open checker let[s] anyone recreate a case without CivicOS").
 *
 * `bundler`'s recipe (`buildMember`, its one expression of the esbuild options: the working directory pinned, symlinks
 * preserved, `node:*` external) bundles `./main.mjs` and the pure check code it imports into one ES module. The program
 * file is that bundle under one first line naming the SHA-256 of everything after it, so the file carries its own
 * fingerprint. The same sources give the same bytes. `./program.mjs` holds the result as text, so the plane serves it
 * (`casechecker`, R15) with no file read; `node bio-plane/src/case-checker/build-program.mjs` rewrites it, and a test
 * fails when it is stale. */

import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildMember, DEFAULT_EXTERNAL } from "../../scripts/fleet-bundle.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const PLANE = resolve(HERE, "..", "..");
const sha = (s) => createHash("sha256").update(s).digest("hex");

/** R13: the program file's text and its fingerprints, built in memory; nothing on disk moves. */
export async function buildProgram() {
  const member = { abs: PLANE, bundle: { entry: "src/case-checker/main.mjs", outfile: "case-checker.mjs", external: [...DEFAULT_EXTERNAL] } };
  const built = await buildMember(member, { write: false });
  const body = built.bytes.toString("utf8");
  const bodySha = sha(body);
  const text = `// Civicsmith case checker (bio-case-file/1). SHA-256 of everything after this line: ${bodySha}\n${body}`;
  return { text, sha256: sha(text), body_sha256: bodySha, inputs: built.inputs.map((i) => i.path) };
}

/** `./program.mjs`' text for a built program. */
export function programModule(p) {
  return "/* GENERATED by ./build-program.mjs (case-checker R13). Do not edit; run `node bio-plane/src/case-checker/build-program.mjs`. */\n"
    + `export const PROGRAM_SHA256 = ${JSON.stringify(p.sha256)};\n`
    + `export const PROGRAM_BODY_SHA256 = ${JSON.stringify(p.body_sha256)};\n`
    + `export const PROGRAM = ${JSON.stringify(p.text)};\n`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const p = await buildProgram();
  writeFileSync(join(HERE, "program.mjs"), programModule(p));
  console.log(`program.mjs written: ${p.text.length} bytes, sha256 ${p.sha256}, ${p.inputs.length} inputs`);
}
