/* steps — THE ROWS (requirements: `build/requirements/steps.md`; T41-17, N820).
 *
 * Each row is `{check, where, translation}`, family C-142, minted here and awaiting the stamp of T42's promotion job.
 * A project's refusals (`PROJECT_SEEN_NOT_A_PARTICIPANT`, `NO_SUCH_PROJECT`, `PROJECT_ACT_NOT_A_PARTICIPANT`) are
 * `membership`'s, relayed; `MINT_EXHAUSTED` is `record-core`'s. No translation names a place. This file imports
 * nothing. */

const at = (...fns) => fns.map((f) => `src/steps/index.mjs ${f}`).join("; ");

export const STEPS_CHECKS = {
  STEP_NO_WORK: { check: "C-142.1", where: at("stepCreate", "stepPropose", "stepAccept"),
    translation: "Say what the work is, in your own words, in at most 500 characters. Nothing was written." },
  STEP_BAD_PLACE: { check: "C-142.2", where: at("stepCreate", "stepPropose", "stepRefer"),
    translation: "A step is taken on one or more questions, in one project, or for the whole group: exactly one of these, and a step is never placed inside another step. Nothing was written." },
  NO_SUCH_BUNDLE: { check: "C-142.3", where: at("stepCreate", "stepRefer", "stepsOn", "questionFollow"),
    translation: "There is no question here by that id that you can see. Nothing was written." },
  STEP_BAD_BY_WHEN: { check: "C-142.4", where: at("stepCreate", "stepByWhen"),
    translation: "A date for a step is a calendar day, with what sets it: the law, a meeting, or your own choice. Nothing was written." },
  STEP_NOT_YOUR_RUN: { check: "C-142.5", where: at("stepCreate", "stepPropose"),
    translation: "The system takes a step only for a run it holds, and this credential holds no such run. Nothing was written." },
  STEP_ALIKE_EXISTS: { check: "C-142.6", where: at("stepCreate"),
    translation: "This work is already an open step on the question. Use that step, or add your question to it. Nothing was written." },
  NO_SUCH_STEP: { check: "C-142.7", where: at("step", "stepStart", "stepEnd", "stepDelete", "stepRefer", "stepProduct", "costMessage"),
    translation: "There is no step here by that id that you can see. Nothing was written." },
  STEP_WAITING: { check: "C-142.8", where: at("stepStart"),
    translation: "This step waits on something not yet met, named here. It starts once each wait is met or removed. Nothing was written." },
  STEP_BAD_END: { check: "C-142.9", where: at("stepEnd"),
    translation: "A step ends as done (ended) or set aside, and only once it is planned or under way. Nothing was written." },
  STEP_BAD_OUTCOME: { check: "C-142.10", where: at("stepEnd", "stepOutcome"),
    translation: "An outcome is helped, a dead end, or not yet judged, recorded for a question the step is on. Nothing was written." },
  STEP_MACHINE_NO_OUTCOME: { check: "C-142.11", where: at("stepEnd"),
    translation: "The system never judges whether a step helped or was a dead end; a member does. It ends its own step with every outcome not yet judged, or sets it aside with its reason. Nothing was written." },
  STEP_NOT_ITS_OWN: { check: "C-142.12", where: at("stepStart", "stepEnd", "stepDelete", "stepWait"),
    translation: "The system acts only on the steps it took itself. Nothing was written." },
  STEP_SHARED_NAME_THE_QUESTION: { check: "C-142.13", where: at("stepDelete"),
    translation: "More than one question uses this step. Name the question whose use of it you are removing. Nothing was written." },
  STEP_WORKED_KEEPS_RECORD: { check: "C-142.14", where: at("stepDelete"),
    translation: "Work was done on this step, so its record is kept. Set it aside instead. Nothing was deleted." },
  STEP_NARROWER_THAN_QUESTION: { check: "C-142.15", where: at("stepRefer"),
    translation: "This step is a project's own, and a question's use of it would show it beyond that project. Take a step on the question instead. Nothing was written." },
  STEP_BAD_PRODUCT: { check: "C-142.16", where: at("stepProduct", "recordProduct"),
    translation: "Name what the step produced by the record's own id: a record, a capture, a passage, a lead or a derived connection with its derivation. Nothing was written." },
  NO_SUCH_PRODUCT: { check: "C-142.17", where: at("stepProduct"),
    translation: "There is nothing here by that id that you can see. Nothing was written." },
  STEP_MEMBER_ONLY: { check: "C-142.18", where: at("stepLearn", "stepOutcome", "stepCostAdd", "stepProduct", "questionFollow", "stepAccept", "costMessage", "stepReminder", "stepByWhen"),
    translation: "Only a member does this, in their own words and by their own choice. Nothing was written." },
  STEP_BAD_TEXT: { check: "C-142.19", where: at("stepLearn", "costMessage", "stepPropose", "stepEnd", "stepAccept"),
    translation: "Write it in your own words, within the length it allows. Nothing was written, and nothing was cut." },
  STEP_BAD_WAIT: { check: "C-142.20", where: at("stepWait"),
    translation: "A step waits on another step, on something arriving, or on a date. Nothing was written." },
  STEP_WAIT_CYCLE: { check: "C-142.21", where: at("stepWait"),
    translation: "This wait would close a loop: the steps named would each wait on the other and none could start. Nothing was written." },
  STEP_WAIT_NARROWER: { check: "C-142.22", where: at("stepWait"),
    translation: "This step would wait on a step fewer people can see, so some who see it could not see what it waits on. Nothing was written." },
  NO_SUCH_WAIT: { check: "C-142.23", where: at("stepWaitRemove"),
    translation: "There is no wait here by that number that you can see. Nothing was written." },
  STEP_BAD_COST: { check: "C-142.24", where: at("stepCostAdd"),
    translation: "A cost is a fee or a purchase: an exact amount, its currency's three-letter code, and what it paid for. Nothing was written." },
  NO_SUCH_COST: { check: "C-142.25", where: at("stepCostRemove"),
    translation: "There is no cost here by that number that you recorded. Nothing was written." },
  STEP_NOT_A_LEG: { check: "C-142.26", where: at("check"),
    translation: "A step is work done toward an answer, never part of what a finding rests on. Rest the finding on what the step found. Nothing was written." },
  STEP_BAD_FORM: { check: "C-142.27", where: at("stepAccept"),
    translation: "A proposed step is taken up as proposed, taken up with your own wording, or set aside for a step of your own. Nothing was written." },
  NO_SUCH_STEP_PROPOSAL: { check: "C-142.28", where: at("stepAccept"),
    translation: "There is no proposed step here by that id that you can see. Nothing was written." },
  STEP_PROPOSAL_DECIDED: { check: "C-142.29", where: at("stepAccept"),
    translation: "This proposed step was already taken up or set aside. Nothing was written." },
  STEP_PROPOSE_NOT_A_MACHINE: { check: "C-142.30", where: at("stepPropose"),
    translation: "A member takes a step themselves; a proposal is the system's or an assistant's. Nothing was written." },
  STEP_BAD_REMINDER: { check: "C-142.31", where: at("stepReminder"),
    translation: "A reminder is set for a calendar day. Nothing was written." },
};
