/* SSHSIG, the OpenSSH detached signature format, verify side.
 *
 * Why this format and not a bare Ed25519 signature: SSHSIG is what
 * `ssh-keygen -Y sign` emits and `ssh-keygen -Y verify` checks, so every
 * signature this system accepts can be produced and independently verified
 * with stock OpenSSH and no BIO code at all. That is the conformance
 * doctrine applied to signing: the reference implementation is OpenSSH
 * itself, and this module must agree with it byte for byte. The test suite
 * pins fixtures generated by real ssh-keygen.
 *
 * Scope is deliberately narrow: ssh-ed25519 keys, sha512 inner hash (what
 * OpenSSH emits by default), signature version 1. Anything else is refused
 * loudly rather than half-supported.
 *
 * Wire shapes, from openssh PROTOCOL.sshsig:
 *
 *   armored:   -----BEGIN SSH SIGNATURE----- base64 -----END SSH SIGNATURE-----
 *   blob:      byte[6] "SSHSIG" | uint32 version=1 | string publickey
 *              | string namespace | string reserved | string hash_algorithm
 *              | string signature
 *   publickey: string "ssh-ed25519" | string key(32)
 *   signature: string "ssh-ed25519" | string sig(64)
 *   signed:    byte[6] "SSHSIG" | string namespace | string reserved
 *              | string hash_algorithm | string H(message)
 *
 * No secrets appear anywhere in this module: it holds public keys and
 * verifies. Signing happens where the private key lives, in the operator's
 * browser (tools/sign-release.html) or in stock ssh-keygen.
 */

const te = new TextEncoder();

const b64ToBytes = (b64) => {
  const bin = atob(b64.replace(/\s+/g, ""));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
};

export const bytesToB64 = (bytes) => {
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
};

/* ssh wire reader: uint32 length-prefixed strings. */
class Rd {
  constructor(buf) { this.b = buf; this.o = 0; }
  bytes(n) {
    if (this.o + n > this.b.length) throw new Error("sshsig: truncated");
    const v = this.b.slice(this.o, this.o + n); this.o += n; return v;
  }
  u32() { const b = this.bytes(4); return (b[0] << 24 | b[1] << 16 | b[2] << 8 | b[3]) >>> 0; }
  str() { return this.bytes(this.u32()); }
  done() { return this.o === this.b.length; }
}

const wStr = (bytes) => {
  const out = new Uint8Array(4 + bytes.length);
  new DataView(out.buffer).setUint32(0, bytes.length);
  out.set(bytes, 4);
  return out;
};
export const cat = (...parts) => {
  const n = parts.reduce((a, p) => a + p.length, 0);
  const out = new Uint8Array(n);
  let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
};

/* Parse an OpenSSH public key line: "ssh-ed25519 AAAA... comment".
   Returns { keyType, raw (32 bytes), b64, comment } or throws. */
export function parsePubkeyLine(line) {
  const m = String(line || "").trim().split(/\s+/);
  if (m.length < 2) throw new Error("pubkey: not an OpenSSH public key line");
  const [keyType, b64] = m;
  if (keyType !== "ssh-ed25519") throw new Error("pubkey: only ssh-ed25519 is supported, got " + keyType);
  const blob = b64ToBytes(b64);
  const r = new Rd(blob);
  const t = new TextDecoder().decode(r.str());
  if (t !== "ssh-ed25519") throw new Error("pubkey: wire type mismatch");
  const raw = r.str();
  if (raw.length !== 32) throw new Error("pubkey: ed25519 key must be 32 bytes");
  return { keyType, raw, b64, comment: m.slice(2).join(" ") };
}

/* Build the OpenSSH wire public key blob from a raw 32-byte ed25519 key,
   and its authorized_keys base64. Used by the signer page and by tests. */
export function wirePubkey(raw) {
  return cat(wStr(te.encode("ssh-ed25519")), wStr(raw));
}

/* Accepts a key in any of the shapes it appears in this system: a bare
   authorized_keys base64 field, a full "ssh-ed25519 AAAA... comment" line,
   or an allowed_signers "principal ssh-ed25519 AAAA..." line. Returns the
   bare base64 of the wire public key, or null if it is not an ed25519 key. */
export function normalizeKey(entry) {
  const toks = String(entry || "").trim().split(/\s+/);
  const i = toks.indexOf("ssh-ed25519");
  const b64 = i >= 0 ? toks[i + 1] : (toks.length === 1 ? toks[0] : null);
  if (!b64 || !b64.startsWith("AAAA")) return null;
  try { return parsePubkeyLine("ssh-ed25519 " + b64).b64; } catch { return null; }
}

const dearmor = (text) => {
  const m = String(text || "").match(
    /-----BEGIN SSH SIGNATURE-----\s*([\s\S]*?)\s*-----END SSH SIGNATURE-----/);
  if (!m) throw new Error("sshsig: missing armor");
  return b64ToBytes(m[1]);
};

/* Parse an armored SSHSIG. Returns fields without verifying anything. */
export function parseSshsig(armored) {
  const blob = dearmor(armored);
  const r = new Rd(blob);
  const magic = new TextDecoder().decode(r.bytes(6));
  if (magic !== "SSHSIG") throw new Error("sshsig: bad magic");
  const version = r.u32();
  if (version !== 1) throw new Error("sshsig: unsupported version " + version);
  const pubkeyBlob = r.str();
  const namespace = new TextDecoder().decode(r.str());
  const reserved = r.str();
  const hashAlg = new TextDecoder().decode(r.str());
  const sigBlob = r.str();

  const pr = new Rd(pubkeyBlob);
  const keyType = new TextDecoder().decode(pr.str());
  if (keyType !== "ssh-ed25519") throw new Error("sshsig: only ssh-ed25519 keys are supported");
  const pubRaw = pr.str();
  if (pubRaw.length !== 32) throw new Error("sshsig: bad ed25519 key length");

  const sr = new Rd(sigBlob);
  const sigType = new TextDecoder().decode(sr.str());
  if (sigType !== "ssh-ed25519") throw new Error("sshsig: signature type mismatch");
  const sigRaw = sr.str();
  if (sigRaw.length !== 64) throw new Error("sshsig: bad ed25519 signature length");

  if (hashAlg !== "sha512" && hashAlg !== "sha256")
    throw new Error("sshsig: unsupported hash " + hashAlg);

  return { version, namespace, hashAlg, reserved, pubRaw, pubkeyBlob, sigRaw,
           pubB64: bytesToB64(wirePubkey(pubRaw)) };
}

/* Verify an armored SSHSIG over a message.
 *
 * message: Uint8Array of the exact signed bytes.
 * expectNamespace: required; a signature from the wrong namespace never
 *   verifies, so a release signature can never be replayed as a
 *   ratification attestation or vice versa.
 * allowedKeys: array of authorized_keys-style base64 strings (the AAAA...
 *   field for ssh-ed25519). The signature's embedded key must be on the
 *   list; SSHSIG carries its own key, so without this check any
 *   self-consistent signature would pass.
 *
 * Returns { ok:true, keyB64, namespace } or { ok:false, reason }.
 * Throws only on malformed input, never on a bad signature.
 */
export async function verifySshsig(armored, message, expectNamespace, allowedKeys) {
  let p;
  try { p = parseSshsig(armored); }
  catch (e) { return { ok: false, reason: "MALFORMED", detail: String(e.message || e) }; }

  if (p.namespace !== expectNamespace)
    return { ok: false, reason: "NAMESPACE", expected: expectNamespace, got: p.namespace };

  const allowed = (allowedKeys || []).map(normalizeKey).filter(Boolean);
  if (!allowed.includes(p.pubB64))
    return { ok: false, reason: "UNKNOWN_KEY", keyB64: p.pubB64 };

  const hash = await crypto.subtle.digest(p.hashAlg === "sha512" ? "SHA-512" : "SHA-256", message);
  const signed = cat(
    te.encode("SSHSIG"),
    wStr(te.encode(p.namespace)),
    wStr(p.reserved),
    wStr(te.encode(p.hashAlg)),
    wStr(new Uint8Array(hash)),
  );

  let key;
  try {
    key = await crypto.subtle.importKey("raw", p.pubRaw, { name: "Ed25519" }, false, ["verify"]);
  } catch (e) {
    return { ok: false, reason: "CRYPTO_UNAVAILABLE", detail: String(e.message || e) };
  }
  const good = await crypto.subtle.verify({ name: "Ed25519" }, key, p.sigRaw, signed);
  return good
    ? { ok: true, keyB64: p.pubB64, namespace: p.namespace }
    : { ok: false, reason: "BAD_SIGNATURE", keyB64: p.pubB64 };
}

/* The canonical statements this system signs. Centralised so the plane, the
   wizard, the signer page, and any future client all sign the same bytes.
   Both are single-line ASCII, so there is no canonicalisation to get wrong. */
export const NS_RELEASE = "bio-release";
export const NS_RATIFY = "bio-ratify";

/* Releases sign the ASSET BYTES themselves, not a statement about them, so a
   verified signature IS the integrity check and cannot diverge from one. */
export const ratifyStatement = (bundleId, bundleSha) =>
  te.encode(`bio-ratify ${bundleId} ${bundleSha}\n`);

/* ---------------------------------------------------------------- the fleet */

/* A SEPARATE NAMESPACE, so a signature over the plane asset can never be
   replayed as a signature over the fleet list, or the reverse. Domain
   separation costs one string here and cannot be retrofitted once signatures
   exist in the wild. */
export const NS_FLEET = "bio-release-fleet";

/* THE ONE PLACE THE FLEET STATEMENT IS BUILT, and the reason it is here rather
   than in the tool that signs it.
   A release carries several assets now — the plane and each fleet member — and
   ONE signature covers the SET. A signature per asset would let anyone serving
   the manifest DROP a member: every remaining signature still verifies and the
   installer silently installs less, which is D-115's "quietly doing less" with
   cryptographic cover.
   The producer (`tools/release-assemble.mjs`) and the verifier (`newgroup`) must
   derive byte-identical statements from the same manifest, and they run in
   different processes on different machines months apart. If each built its own
   string, the first divergence would present as "signature invalid" on a release
   that is perfectly good — indistinguishable from an attack, and debugged by
   whoever is least equipped to. So neither builds it: both call this.
   The PLANE LINE IS PART OF THE STATEMENT on purpose. It is what makes the
   signature say "these members were built against THIS plane", which is the
   claim D-298 found unbacked when a month-old plane was nearly published beside
   fleet bundles compiled from today's plane source.
   Sorted by member, so two assemblers of the same tree emit the same bytes.

   THE SERVICE BINDINGS ARE PART OF THE STATEMENT, and that is deliberate rather
   than thorough. The installer cannot give every member the same bindings:
   `pdf-worker` declares NONE on purpose ("the narrowest binding that does the
   job" — it structurally cannot reach the record), while `agent-worker` needs
   PLANE. So the per-member binding set has to travel in the manifest, and
   anything the installer ACTS ON from the manifest must be signed or it is a
   value an attacker can choose. The targets travel as WRITTEN in the member's
   config — the phantom `bio-plane` included — and the installer substitutes the
   instance slug at upload; so what is signed is the SHAPE, and the slug can
   never come from the network. Rendering is `NAME:target`, sorted by binding
   name, comma-joined, and the `services=` key is always present so a member
   with none is stated rather than omitted. */
const renderServices = (services) => [...(services || [])]
  .map((s) => `${s.binding}:${s.service}`)
  .sort()
  .join(",");

/* A MEMBER IS NOT ALWAYS ONE FILE, and the signature has to say so.
   `ocr-worker` (CPDF-10 / IC-78) ships its bundle PLUS two upload parts — a
   tesseract wasm core and a language model, 5.95 MB between them — declared
   `external` so esbuild does not inline them and `assets` so FL-9's guard hashes
   them. An installer must upload all three or the member deploys and fails at
   runtime with no engine.
   SIGNING ONLY THE BUNDLE WOULD HAVE BEEN WORSE THAN INCOMPLETE. The engine's
   measured fidelity (CPDF-15) is a fidelity OF THOSE EXACT BYTES, and the
   provenance chain this member produces names a `cap` that rests on it — so a
   swapped model or wasm core changes what the record claims while every
   signature still verified. That is the record claiming more than it can
   support, with cryptographic cover.
   Rendered `path:sha256:bytes`, sorted by path, and `parts=` is always present
   so a member with none is STATED rather than omitted — absent and empty must
   not look alike, here as everywhere else in this statement. */
const renderParts = (parts) => [...(parts || [])]
  .map((p) => `${p.path}:${p.sha256}:${p.bytes}`)
  .sort()
  .join(",");

export const fleetStatement = ({ version, plane, members }) =>
  `${NS_FLEET}/1\n`
  + `version ${version}\n`
  + `plane ${plane.sha256} ${plane.bytes} ${plane.asset}\n`
  + [...members]
      .sort((a, b) => (a.member < b.member ? -1 : a.member > b.member ? 1 : 0))
      .map((m) => `member ${m.member} ${m.sha256} ${m.bytes} ${m.asset}`
        + ` services=${renderServices(m.services)}`
        + ` parts=${renderParts(m.parts)}`)
      .join("\n")
  + "\n";

/* CASE-5b / DEC-72: THE CASE DOCUMENT'S STATEMENT, and it is a SEPARATE
   statement rather than `ratifyStatement` reused with a case id in the bundle
   slot. Two reasons, and the second is the load-bearing one.

   (1) A case edition is identified by a PAIR — `(case_id, edition)` — where a
   bundle is identified by its id alone, its edition living inside the bytes. A
   statement that dropped the edition would have one signature standing for every
   edition of a case, which is the same defect EDITION_EXISTS refuses one level
   down.

   (2) AND IT IS DOMAIN SEPARATION, not decoration. `ratifyStatement` is the
   sentence a member signs over a FINDING. If a case document could be signed
   with a statement of that exact shape, a signature gathered for one act would
   verify for the other the moment an identifier collided — and case ids and
   bundle ids are both allocId-minted strings. The leading token differs, so the
   two message spaces cannot overlap no matter what the identifiers do.

   The NAMESPACE stays `bio-ratify`: it is the SSHSIG namespace this instance's
   signers already have configured, and splitting it would make every existing
   signer page and wizard wrong for an act they are perfectly entitled to
   perform. The separation is in the message, which is where a verifier looks. */
export const caseRatifyStatement = (caseId, edition, docSha) =>
  te.encode(`bio-ratify-case ${caseId} ${edition} ${docSha}\n`);
