/* wizard-scripts: writes the carried data from the design stream's files (R13, R22; DEC-139 (5), DEC-148).
 *
 *   node bio-plane/src/wizard-scripts/build-data.mjs <registry.json> <registry-commit> <library.json> <library-commit>
 *                                                    [<newer-library.json> <newer-commit>]...
 *
 * Reads each file as it stands at its own commit (the commits the job's START names: since T37 the registry re-taken
 * from PR #19's merge to `main`, `3660c18803`, since T41; the library's version 1 kept at `d129238bf3`, DEC-148's,
 * R22, K1790; with newer libraries, the versions BOB adopts from each, `LIBRARY_ADOPTED`, K2241) and writes `screen-registry.mjs` and
 * `civicsmith-library.mjs` beside this file, each naming its own source's commit, path and SHA-256. A run on the same
 * files writes the same bytes. Not part of the bundle: nothing imports it, and importing it (as a test that reads every
 * module file does) writes nothing: it runs only as a command. */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256HexSync } from "../record-grammar/sha256.mjs";
import { screensFromFile, libraryFromFile, adoptedLibrary } from "./data.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const lines = (list) => `[\n${list.map((x) => `  ${JSON.stringify(x)},`).join("\n")}\n]`;

const REGISTRY_HEAD = `/* GENERATED by build-data.mjs from the design stream's screen registry (wizard-scripts R13; DEC-139 (5);
 * K1565): every screen with its id, name and purpose, its declared and function acts as ops in the file's order, and
 * its owed acts apart, each with the number of acts before it. Do not edit: run build-data.mjs. */
import { deepFreeze } from "./data.mjs";
`;
const LIBRARY_HEAD = `/* GENERATED by build-data.mjs from the design stream's Civicsmith library (wizard-scripts R1, R13, R14, R22; DEC-121
 * (1), (9); DEC-148, Bob's "S2: approved", 2026-10-06; K1784, K1785, K1790): the seventeen scripts shipped with the
 * release, read-only to every group, each version authored by the Civicsmith library; three required.
 * \`plane\` passes it to \`wizardRegister\` at start (a call without \`library\` registers it); the release suite runs
 * \`requiredFailures\` over it. A later version is carried only as BOB adopts it (K2241). Do not edit: run build-data.mjs.
 *
 * An entry: \`{id, name, start, origin, scope, required, version, steps, author, approved: {by, at, ruling?}, source,
 * earlier?}\`: \`source\` the commit its steps come from; \`earlier\` each earlier version, \`[{version, steps, author,
 * approved, source}]\`, when BOB has adopted a newer one (R22; K2241). */
import { deepFreeze } from "./data.mjs";
`;

const COMMIT = /^[0-9a-f]{7,40}$/;

function main([registryPath, registryCommit, libraryPath, libraryCommit, ...rest]) {
  const pairs = [];
  for (let i = 0; i < rest.length; i += 2) pairs.push({ path: rest[i], commit: rest[i + 1] });
  if (!registryPath || !libraryPath || !COMMIT.test(registryCommit || "") || !COMMIT.test(libraryCommit || "")
      || pairs.some((p) => !p.path || !COMMIT.test(p.commit || ""))) {
    console.error("usage: build-data.mjs <registry.json> <registry-commit> <library.json> <library-commit> [<newer-library.json> <newer-commit>]...");
    process.exitCode = 2;
    return;
  }
  const source = (commit, path, text) => ({ commit, path: `docs/development/ux-substrate/screens/${path}`, sha256: sha256HexSync(text) });
  const regText = readFileSync(registryPath, "utf8");
  const libText = readFileSync(libraryPath, "utf8");
  const screens = screensFromFile(JSON.parse(regText));
  const newer = pairs.map((p) => ({ ...p, text: readFileSync(p.path, "utf8") }));
  const library = newer.length ? adoptedLibrary(JSON.parse(libText), libraryCommit, newer.map((n) => ({ file: JSON.parse(n.text), commit: n.commit })))
    : libraryFromFile(JSON.parse(libText), libraryCommit);
  writeFileSync(join(here, "screen-registry.mjs"), `${REGISTRY_HEAD}
export const SCREEN_REGISTRY_SOURCE = deepFreeze(${JSON.stringify(source(registryCommit, "registry.json", regText))});

export const SCREEN_REGISTRY = deepFreeze(${lines(screens)});
`);
  writeFileSync(join(here, "civicsmith-library.mjs"), `${LIBRARY_HEAD}
export const CIVICSMITH_LIBRARY_SOURCE = deepFreeze(${JSON.stringify(source(libraryCommit, "library.json", libText))});

/** R22 (K2241): the newer libraries BOB's adopted versions come from, each at its own commit (\`LIBRARY_ADOPTED\`). */
export const CIVICSMITH_LIBRARY_ADOPTED_SOURCES = deepFreeze(${lines(newer.map((n) => source(n.commit, "library.json", n.text)))});

export const CIVICSMITH_LIBRARY = deepFreeze(${lines(library)});
`);
  console.log(`wrote ${screens.length} screens and ${library.length} scripts (registry ${registryCommit}, library ${libraryCommit}`
    + `${newer.length ? `, adopted: ${library.filter((e) => e.earlier).map((e) => `${e.name} v${e.version} from ${e.source}`).join(", ")}` : ""})`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main(process.argv.slice(2));
