/* wizard-scripts: writes the carried data from the design stream's files (R13, R22; DEC-139 (5), DEC-148).
 *
 *   node bio-plane/src/wizard-scripts/build-data.mjs <registry.json> <library.json> <commit>
 *
 * Reads the two files as they stand at `<commit>` of the design branch (the commit the job's START names, K1790) and
 * writes `screen-registry.mjs` and `civicsmith-library.mjs` beside this file, each naming its source's commit, path and
 * SHA-256. A run on the same files writes the same bytes. Not part of the bundle: nothing imports it, and importing it
 * (as a test that reads every module file does) writes nothing: it runs only as a command. */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sha256HexSync } from "../record-grammar/sha256.mjs";
import { screensFromFile, libraryFromFile } from "./data.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const lines = (list) => `[\n${list.map((x) => `  ${JSON.stringify(x)},`).join("\n")}\n]`;

const REGISTRY_HEAD = `/* GENERATED by build-data.mjs from the design stream's screen registry (wizard-scripts R13; DEC-139 (5);
 * K1565): every screen with its id, name and purpose, its declared and function acts as ops in the file's order, and
 * its owed acts apart, each with the number of acts before it. Do not edit: run build-data.mjs. */
import { deepFreeze } from "./data.mjs";
`;
const LIBRARY_HEAD = `/* GENERATED by build-data.mjs from the design stream's Civicsmith library (wizard-scripts R1, R13, R14, R22; DEC-121
 * (1), (9); DEC-148, Bob's "S2: approved", 2026-10-06; K1784, K1785, K1790): the seventeen scripts shipped with the
 * release, read-only to every group, each one approved version authored by the Civicsmith library; three required.
 * \`plane\` passes it to \`wizardRegister\` at start (a call without \`library\` registers it); the release suite runs
 * \`requiredFailures\` over it. A later version is carried only when Bob approves it. Do not edit: run build-data.mjs.
 *
 * An entry: \`{id, name, start, origin, scope, required, version, steps, author, approved: {by, at}}\`. */
import { deepFreeze } from "./data.mjs";
`;

function main([registryPath, libraryPath, commit]) {
  if (!registryPath || !libraryPath || !/^[0-9a-f]{7,40}$/.test(commit || "")) {
    console.error("usage: build-data.mjs <registry.json> <library.json> <commit>");
    process.exitCode = 2;
    return;
  }
  const source = (path, text) => ({ commit, path: `docs/development/ux-substrate/screens/${path}`, sha256: sha256HexSync(text) });
  const regText = readFileSync(registryPath, "utf8");
  const libText = readFileSync(libraryPath, "utf8");
  const screens = screensFromFile(JSON.parse(regText));
  const library = libraryFromFile(JSON.parse(libText));
  writeFileSync(join(here, "screen-registry.mjs"), `${REGISTRY_HEAD}
export const SCREEN_REGISTRY_SOURCE = deepFreeze(${JSON.stringify(source("registry.json", regText))});

export const SCREEN_REGISTRY = deepFreeze(${lines(screens)});
`);
  writeFileSync(join(here, "civicsmith-library.mjs"), `${LIBRARY_HEAD}
export const CIVICSMITH_LIBRARY_SOURCE = deepFreeze(${JSON.stringify(source("library.json", libText))});

export const CIVICSMITH_LIBRARY = deepFreeze(${lines(library)});
`);
  console.log(`wrote ${screens.length} screens and ${library.length} scripts from ${commit}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main(process.argv.slice(2));
